// Code generated by "stringer -type=Context"; DO NOT EDIT.

package wip

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Other-0]
	_ = x[Blocker-1]
	_ = x[InProgress-2]
	_ = x[NeedsDecision-3]
	_ = x[Idea-4]
	_ = x[Question-5]
	_ = x[FixAttempt-6]
	_ = x[ImplementationTodo-7]
	_ = x[ImplementationParial-8]
	_ = x[ImplementationNeedsReview-9]
	_ = x[Testing-10]
	_ = x[TestingUntested-11]
	_ = x[TestingFailing-12]
	_ = x[TestingMissingCoverage-13]
	_ = x[TestingIntegrationNeeded-14]
	_ = x[TestingMissingUnitTest-15]
	_ = x[TestingMissingEndToEndTest-16]
	_ = x[TestingStress-17]
	_ = x[TestingUserInterface-18]
	_ = x[TestingUserExperience-19]
	_ = x[Benchmark-20]
	_ = x[BenchmarkIntegration-21]
	_ = x[BenchmarkCost-22]
	_ = x[TechincalDebt-23]
	_ = x[TechnicalDebtWorkaround-24]
	_ = x[TechnicalDebtRefactoringNeeded-25]
	_ = x[TechnicalDebtOptimizationOpportunity-26]
	_ = x[Dependency-27]
	_ = x[DependenciesExternalBlocker-28]
	_ = x[DependenciesVeresionUpdate-29]
	_ = x[DependenciesIntegrationPoint-30]
	_ = x[Documentation-31]
	_ = x[DocumentationCodeComment-32]
	_ = x[DocumentationApiDoc-33]
	_ = x[DocumentationUserDoc-34]
	_ = x[DocumentationMigrationGuide-35]
	_ = x[DoucmentationBuildGuide-36]
	_ = x[DocumentationDesignDocument-37]
	_ = x[DocumentationInfrastructureDocument-38]
	_ = x[DocumentationArchitectureDocument-39]
	_ = x[KnownIssue-40]
	_ = x[KnownIssueError-41]
	_ = x[KnownIssueUpdate-42]
	_ = x[UpperBound-43]
}

const _Context_name = "OtherBlockerInProgressNeedsDecisionIdeaQuestionFixAttemptImplementationTodoImplementationParialImplementationNeedsReviewTestingTestingUntestedTestingFailingTestingMissingCoverageTestingIntegrationNeededTestingMissingUnitTestTestingMissingEndToEndTestTestingStressTestingUserInterfaceTestingUserExperienceBenchmarkBenchmarkIntegrationBenchmarkCostTechincalDebtTechnicalDebtWorkaroundTechnicalDebtRefactoringNeededTechnicalDebtOptimizationOpportunityDependencyDependenciesExternalBlockerDependenciesVeresionUpdateDependenciesIntegrationPointDocumentationDocumentationCodeCommentDocumentationApiDocDocumentationUserDocDocumentationMigrationGuideDoucmentationBuildGuideDocumentationDesignDocumentDocumentationInfrastructureDocumentDocumentationArchitectureDocumentKnownIssueKnownIssueErrorKnownIssueUpdateUpperBound"

var _Context_index = [...]uint16{0, 5, 12, 22, 35, 39, 47, 57, 75, 95, 120, 127, 142, 156, 178, 202, 224, 250, 263, 283, 304, 313, 333, 346, 359, 382, 412, 448, 458, 485, 511, 539, 552, 576, 595, 615, 642, 665, 692, 727, 760, 770, 785, 801, 811}

func (i Context) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Context_index)-1 {
		return "Context(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Context_name[_Context_index[idx]:_Context_index[idx+1]]
}
