// Code generated by "stringer -type=Scope"; DO NOT EDIT.

package scope

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Other-0]
	_ = x[Accessibility-1]
	_ = x[Alpha-2]
	_ = x[Analytics-3]
	_ = x[Android-4]
	_ = x[Api-5]
	_ = x[Auth-6]
	_ = x[Backend-7]
	_ = x[Benchmark-8]
	_ = x[Beta-9]
	_ = x[Build-10]
	_ = x[Cd-11]
	_ = x[Chore-12]
	_ = x[Ci-13]
	_ = x[Cli-14]
	_ = x[Compliance-15]
	_ = x[Components-16]
	_ = x[Config-17]
	_ = x[Database-18]
	_ = x[Db-19]
	_ = x[Dependencies-20]
	_ = x[Deps-21]
	_ = x[Devops-22]
	_ = x[Docs-23]
	_ = x[Drizzle-24]
	_ = x[E2e-25]
	_ = x[Feat-26]
	_ = x[Fix-27]
	_ = x[Infra-28]
	_ = x[Internationalization-29]
	_ = x[Ios-30]
	_ = x[Kubernetes-31]
	_ = x[Kustomize-32]
	_ = x[Legal-33]
	_ = x[Localization-34]
	_ = x[Logging-35]
	_ = x[Mobile-36]
	_ = x[Perf-37]
	_ = x[Plumbing-38]
	_ = x[PreRelease-39]
	_ = x[Prisma-40]
	_ = x[Profiling-41]
	_ = x[Refactor-42]
	_ = x[Release-43]
	_ = x[ReleaseCandidate-44]
	_ = x[Scripts-45]
	_ = x[SearchEngineOptimization-46]
	_ = x[Security-47]
	_ = x[Server-48]
	_ = x[Testing-49]
	_ = x[Tests-50]
	_ = x[Tracking-51]
	_ = x[Translation-52]
	_ = x[Types-53]
	_ = x[Ui-54]
	_ = x[UnitTests-55]
	_ = x[Ux-56]
	_ = x[Vendor-57]
	_ = x[UpperBound-58]
}

const _Scope_name = "OtherAccessibilityAlphaAnalyticsAndroidApiAuthBackendBenchmarkBetaBuildCdChoreCiCliComplianceComponentsConfigDatabaseDbDependenciesDepsDevopsDocsDrizzleE2eFeatFixInfraInternationalizationIosKubernetesKustomizeLegalLocalizationLoggingMobilePerfPlumbingPreReleasePrismaProfilingRefactorReleaseReleaseCandidateScriptsSearchEngineOptimizationSecurityServerTestingTestsTrackingTranslationTypesUiUnitTestsUxVendorUpperBound"

var _Scope_index = [...]uint16{0, 5, 18, 23, 32, 39, 42, 46, 53, 62, 66, 71, 73, 78, 80, 83, 93, 103, 109, 117, 119, 131, 135, 141, 145, 152, 155, 159, 162, 167, 187, 190, 200, 209, 214, 226, 233, 239, 243, 251, 261, 267, 276, 284, 291, 307, 314, 338, 346, 352, 359, 364, 372, 383, 388, 390, 399, 401, 407, 417}

func (i Scope) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Scope_index)-1 {
		return "Scope(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Scope_name[_Scope_index[idx]:_Scope_index[idx+1]]
}
