// Code generated by "stringer -type=Mode"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModeJSON-0]
	_ = x[ModeYAML-1]
}

const _Mode_name = "ModeJSONModeYAML"

var _Mode_index = [...]uint8{0, 8, 16}

func (i Mode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Mode_index)-1 {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[idx]:_Mode_index[idx+1]]
}
